# Generated by Django 4.1.5 on 2023-11-22 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmer',
            name='Percent',
        ),
        migrations.RemoveField(
            model_name='programmer',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='programmer',
            name='country',
        ),
    ]
